import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve as resolvePath } from 'node:path';
import { test } from 'node:test';

// The generator has no in-process seam — it shells out to `find`, calls
// build() twice at module scope, and exports nothing — so it is exercised as a
// subprocess against a throwaway standards tree, exactly as cli.test.ts drives
// the CLI. Both repo-layout literals it carries (the `src/standards/` write
// target and the `../../` import depth) are only observable this way: the
// import depth is asserted by RESOLVING each emitted specifier from the
// barrel's own directory, so a wrong number of `../` segments fails even
// though the string itself is well-formed.
const TOOL = join(process.cwd(), 'tools', 'generateStandardsBarrels.mjs');

/**
 * A throwaway repo holding only what the generator reads and writes: the two
 * standards trees it walks and the `src/standards/` directory it writes into
 * (the generator never creates that directory itself).
 */
const setupStandardsRepo = ({ code = [], tests = [] }: { code?: string[]; tests?: string[] } = {}) => {
	const cwd = mkdtempSync(join(tmpdir(), 'lightsout-barrels-'));

	mkdirSync(join(cwd, 'standards/code'), { recursive: true });
	mkdirSync(join(cwd, 'standards/tests'), { recursive: true });
	mkdirSync(join(cwd, 'src/standards'), { recursive: true });

	[...code.map((file) => `standards/code/${file}`), ...tests.map((file) => `standards/tests/${file}`)].forEach((file) => {
		mkdirSync(dirname(join(cwd, file)), { recursive: true });
		writeFileSync(join(cwd, file), `# ${file}\n`);
	});

	return cwd;
};

const runGenerator = ({ cwd }: { cwd: string }) =>
	new Promise<{ stdout: string; stderr: string; code: number | null }>((resolve, reject) => {
		const child = spawn(process.execPath, [TOOL], { cwd });

		let stdout = '';
		let stderr = '';

		child.stdout.on('data', (chunk) => {
			stdout += chunk;
		});
		child.stderr.on('data', (chunk) => {
			stderr += chunk;
		});
		child.on('error', reject);
		child.on('close', (code) => resolve({ stdout, stderr, code }));
	});

const readBarrel = ({ cwd, exportName }: { cwd: string; exportName: string }) =>
	readFileSync(join(cwd, 'src/standards', `${exportName}.ts`), 'utf8');

/** Every `import docN from '<specifier>';` line, in emitted order. */
const importSpecifiers = ({ source }: { source: string }) =>
	[...source.matchAll(/^import doc(\d+) from '([^']+)';$/gm)].map(([, index, specifier]) => ({ index: Number(index), specifier }));

/** Each `<channel>: [ ... ].join(...)` block with the docs and source files it lists, in emitted order. */
const channelBlocks = ({ source }: { source: string }) =>
	[...source.matchAll(/^\t(\w+): \[\n([\s\S]*?)\n\t\]\.join/gm)].map(([, channel, body]) => ({
		channel,
		docs: [...body.matchAll(/\$\{doc(\d+)\}/g)].map(([, index]) => Number(index)),
		files: [...body.matchAll(/lightsout defaults: (\S+) -->/g)].map(([, file]) => file),
	}));

test('one run writes both barrels under src/standards, each declaring its own export', async () => {
	const cwd = setupStandardsRepo({ code: ['style/casing.md'], tests: ['unit/unit-testing.md'] });

	const { stderr, code } = await runGenerator({ cwd });

	const codeBarrel = readBarrel({ cwd, exportName: 'defaultCodeStandards' });
	const testBarrel = readBarrel({ cwd, exportName: 'defaultTestStandards' });

	assert.equal(code, 0);
	assert.equal(stderr, '');
	assert.ok(codeBarrel.includes('export const defaultCodeStandards: Record<string, string> = {'), 'readStandards imports this barrel by name');
	assert.ok(testBarrel.includes('export const defaultTestStandards: Record<string, string> = {'), 'readStandards imports this barrel by name');
	assert.match(codeBarrel, /^\/\/ GENERATED by tools\/generateStandardsBarrels\.mjs from standards\/code\/ .*do not edit by hand\.$/m);
	assert.match(testBarrel, /^\/\/ GENERATED by tools\/generateStandardsBarrels\.mjs from standards\/tests\/ .*do not edit by hand\.$/m);
});

test('each emitted import specifier resolves from the barrel directory back to its standards doc', async () => {
	const cwd = setupStandardsRepo({ code: ['architecture/folder-structure.md', 'style/casing.md'], tests: ['unit/unit-testing.md'] });

	const { code } = await runGenerator({ cwd });

	const specifiers = importSpecifiers({ source: readBarrel({ cwd, exportName: 'defaultCodeStandards' }) });

	assert.equal(code, 0);
	assert.deepEqual(
		specifiers.map(({ index, specifier }) => ({ index, resolved: resolvePath(join(cwd, 'src/standards'), specifier) })),
		[
			{ index: 0, resolved: join(cwd, 'standards/code/architecture/folder-structure.md') },
			{ index: 1, resolved: join(cwd, 'standards/code/style/casing.md') },
		],
		'the barrel sits two levels below the repo root, so every specifier must climb exactly that far',
	);
});

test('the test-tree barrel resolves its specifiers from the same depth', async () => {
	const cwd = setupStandardsRepo({ code: ['style/casing.md'], tests: ['unit/jest/unit-testing.md'] });

	const { code } = await runGenerator({ cwd });

	const specifiers = importSpecifiers({ source: readBarrel({ cwd, exportName: 'defaultTestStandards' }) });

	assert.equal(code, 0);
	assert.deepEqual(
		specifiers.map(({ specifier }) => resolvePath(join(cwd, 'src/standards'), specifier)),
		[join(cwd, 'standards/tests/unit/jest/unit-testing.md')],
	);
});

test('docs are imported in sorted path order and each entry carries its own repo-relative marker', async () => {
	const cwd = setupStandardsRepo({ code: ['zeta.md', 'alpha.md', 'middle.md'], tests: ['unit/one.md'] });

	const { code } = await runGenerator({ cwd });

	const source = readBarrel({ cwd, exportName: 'defaultCodeStandards' });

	assert.equal(code, 0);
	assert.deepEqual(
		importSpecifiers({ source }).map(({ specifier }) => specifier),
		['../../standards/code/alpha.md', '../../standards/code/middle.md', '../../standards/code/zeta.md'],
	);
	assert.deepEqual(channelBlocks({ source }), [
		{
			channel: 'base',
			docs: [0, 1, 2],
			files: ['standards/code/alpha.md', 'standards/code/middle.md', 'standards/code/zeta.md'],
		},
	]);
});

test('docs are grouped into base, react, and tanstack channels by path', async () => {
	const cwd = setupStandardsRepo({ code: ['architecture/plain.md', 'react/components.md', 'tanstack-start/routing.md'], tests: ['unit/one.md'] });

	const { stdout, code } = await runGenerator({ cwd });

	const blocks = channelBlocks({ source: readBarrel({ cwd, exportName: 'defaultCodeStandards' }) });

	assert.equal(code, 0);
	assert.deepEqual(blocks, [
		{ channel: 'base', docs: [0], files: ['standards/code/architecture/plain.md'] },
		{ channel: 'react', docs: [1], files: ['standards/code/react/components.md'] },
		{ channel: 'tanstack', docs: [2], files: ['standards/code/tanstack-start/routing.md'] },
	]);
	assert.ok(stdout.includes('defaultCodeStandards.ts: 3 docs across channels [base, react, tanstack]'), 'the run reports what it grouped');
});

test('a path naming both frameworks lands in the tanstack channel', async () => {
	const cwd = setupStandardsRepo({ code: ['react/tanstack-query.md'], tests: ['unit/one.md'] });

	const { code } = await runGenerator({ cwd });

	const blocks = channelBlocks({ source: readBarrel({ cwd, exportName: 'defaultCodeStandards' }) });

	assert.equal(code, 0);
	assert.deepEqual(blocks, [{ channel: 'tanstack', docs: [0], files: ['standards/code/react/tanstack-query.md'] }]);
});

test('an empty tree yields a barrel with no imports and no channels, and does not stop the other tree', async () => {
	const cwd = setupStandardsRepo({ code: [], tests: ['unit/one.md'] });

	const { stdout, code } = await runGenerator({ cwd });

	const emptyBarrel = readBarrel({ cwd, exportName: 'defaultCodeStandards' });
	const testBarrel = readBarrel({ cwd, exportName: 'defaultTestStandards' });

	assert.equal(code, 0);
	assert.deepEqual(importSpecifiers({ source: emptyBarrel }), [], 'the blank `find` line is filtered out rather than imported');
	assert.deepEqual(channelBlocks({ source: emptyBarrel }), []);
	assert.ok(emptyBarrel.includes('export const defaultCodeStandards: Record<string, string> = {'));
	assert.deepEqual(importSpecifiers({ source: testBarrel }).map(({ specifier }) => specifier), ['../../standards/tests/unit/one.md']);
	assert.equal(stdout, 'defaultCodeStandards.ts: 0 docs across channels []\ndefaultTestStandards.ts: 1 docs across channels [base]\n');
});
