/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RepoStandardsRouteImport } from './routes/repo.standards'
import { Route as RepoRunsRouteImport } from './routes/repo.runs'
import { Route as RepoRunsRunIdRouteImport } from './routes/repo.runs_.$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoStandardsRoute = RepoStandardsRouteImport.update({
  id: '/repo/standards',
  path: '/repo/standards',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoRunsRoute = RepoRunsRouteImport.update({
  id: '/repo/runs',
  path: '/repo/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoRunsRunIdRoute = RepoRunsRunIdRouteImport.update({
  id: '/repo/runs_/$runId',
  path: '/repo/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/repo/runs': typeof RepoRunsRoute
  '/repo/standards': typeof RepoStandardsRoute
  '/repo/runs/$runId': typeof RepoRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/repo/runs': typeof RepoRunsRoute
  '/repo/standards': typeof RepoStandardsRoute
  '/repo/runs/$runId': typeof RepoRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/repo/runs': typeof RepoRunsRoute
  '/repo/standards': typeof RepoStandardsRoute
  '/repo/runs_/$runId': typeof RepoRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/repo/runs' | '/repo/standards' | '/repo/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/repo/runs' | '/repo/standards' | '/repo/runs/$runId'
  id: '__root__' | '/' | '/repo/runs' | '/repo/standards' | '/repo/runs_/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RepoRunsRoute: typeof RepoRunsRoute
  RepoStandardsRoute: typeof RepoStandardsRoute
  RepoRunsRunIdRoute: typeof RepoRunsRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo/standards': {
      id: '/repo/standards'
      path: '/repo/standards'
      fullPath: '/repo/standards'
      preLoaderRoute: typeof RepoStandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo/runs': {
      id: '/repo/runs'
      path: '/repo/runs'
      fullPath: '/repo/runs'
      preLoaderRoute: typeof RepoRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo/runs_/$runId': {
      id: '/repo/runs_/$runId'
      path: '/repo/runs/$runId'
      fullPath: '/repo/runs/$runId'
      preLoaderRoute: typeof RepoRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RepoRunsRoute: RepoRunsRoute,
  RepoStandardsRoute: RepoStandardsRoute,
  RepoRunsRunIdRoute: RepoRunsRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
