// GENERATED by tools/generateStandardsBarrels.mjs from standards/tests/ — do not edit by hand.
import doc0 from '../../../standards/tests/unit/jest/unit-test-examples.md';
import doc1 from '../../../standards/tests/unit/jest/unit-testing-react-components.md';
import doc2 from '../../../standards/tests/unit/jest/unit-testing.md';

/** Every default tests standards doc, concatenated in path order with per-file provenance headers. */
export const defaultTestStandards = [
	`<!-- lightsout defaults: standards/tests/unit/jest/unit-test-examples.md -->\n${doc0}`,
	`<!-- lightsout defaults: standards/tests/unit/jest/unit-testing-react-components.md -->\n${doc1}`,
	`<!-- lightsout defaults: standards/tests/unit/jest/unit-testing.md -->\n${doc2}`,
].join('\n\n');
