// GENERATED by tools/generateStandardsBarrels.mjs from standards/tests/ — do not edit by hand.
import doc0 from '../../../standards/tests/unit/jest/unit-test-examples.md';
import doc1 from '../../../standards/tests/unit/jest/unit-testing-react-components.md';
import doc2 from '../../../standards/tests/unit/jest/unit-testing.md';

/** Default tests standards docs by channel: base always applies; framework channels apply when the package scope uses that framework. */
export const defaultTestStandards: Record<string, string> = {
	base: [
		`<!-- lightsout defaults: standards/tests/unit/jest/unit-test-examples.md -->\n${doc0}`,
		`<!-- lightsout defaults: standards/tests/unit/jest/unit-testing.md -->\n${doc2}`,
	].join('\n\n'),
	react: [
		`<!-- lightsout defaults: standards/tests/unit/jest/unit-testing-react-components.md -->\n${doc1}`,
	].join('\n\n'),
};
