/** Stable discriminants shared by the planning record, role boundary and consumers. */
export const PlanningVocabulary = {
	Dispute: { ConflictingReports: 'conflicting-reports', AmbiguousObligation: 'ambiguous-obligation', ContestedResolution: 'contested-resolution' },
	UnknownAssessment: { Unavailable: 'required-unavailable', Acquired: 'required-acquired', Unnecessary: 'not-required' },
	Observation: { Content: 'content', Absence: 'absence', Membership: 'membership', Presence: 'presence' },
	Stage: { Brainstorm: 'brainstorm', Implementation: 'implementation' },
	Target: { Alignment: 'brainstorm-alignment', Implementation: 'implementation' },
	ClaimKind: {
		Requirement: 'requirement',
		Decision: 'decision',
		Constraint: 'constraint',
		Architecture: 'architecture',
		Contract: 'contract',
		Acceptance: 'acceptance',
		Question: 'question',
	},
	Owner: { User: 'user', Planner: 'planner', Implementer: 'implementer' },
	ClaimState: { Unresolved: 'unresolved', Settled: 'settled', Superseded: 'superseded' },
	Role: {
		Investigate: 'investigate',
		Architect: 'architect',
		DesignReview: 'design-review',
		Draft: 'draft',
		ImplementationReview: 'implementation-review',
		IntegrationReview: 'integration-review',
		Repair: 'repair',
		Adjudicate: 'adjudicate',
		Diagnose: 'diagnose',
	},
	WorkState: { Pending: 'pending', Running: 'running', Complete: 'complete', Interrupted: 'interrupted' },
	FindingState: { Open: 'open', Repairing: 'repairing', Verified: 'verified', Withdrawn: 'withdrawn' },
	Severity: { Blocking: 'blocking', Advisory: 'advisory' },
	Scope: { WholePlan: 'whole-plan', Selected: 'selected' },
	Dependency: {
		Content: 'content',
		Absence: 'absence',
		Search: 'search',
		Membership: 'membership',
		Collection: 'collection',
		Unknown: 'unknown',
	},
	DependencyReach: { Known: 'known', Unknown: 'unknown' },
	Collection: { Claims: 'claims', Phases: 'phases', Exports: 'exports', Reviews: 'reviews' },
	Operation: { ReadFile: 'read-file', ReadRange: 'read-range', List: 'list', Search: 'search' },
	ResultKind: { Terminal: 'terminal', EvidenceRequest: 'evidence-request' },
	Status: { Complete: 'complete', Aligned: 'aligned', AwaitingUser: 'awaiting-user', ExternallyBlocked: 'externally-blocked' },
	Review: { Adequate: 'adequate', Insufficient: 'insufficient' },
	Disposition: { Repair: 'repair', Withdraw: 'withdraw', Escalate: 'escalate' },
	Channel: { Code: 'code', Test: 'test', Docs: 'docs' },
	ConfirmationChannel: { Foreground: 'foreground', Relay: 'relay' },
	Artifact: { Single: 'single', Overview: 'overview', Phase: 'phase', Data: 'data' },
	Acceptance: { Test: 'test', Prose: 'prose' },
} as const;
