import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { parse } from 'yaml';
import { ConnectionDoc } from '@lightsout/contracts';

const frontmatterPattern = /^---\n([\s\S]*?)\n---/;

interface Params {
	connectionsDir: string;
}

/**
 * Rebuild INDEX.md from the docs themselves — a human convenience the
 * engine regenerates mechanically (and never trusts as input; the docs
 * directory is the routing truth). The summary column is each doc's first
 * body line.
 */
export const regenerateConnectionIndex = async ({ connectionsDir }: Params) => {
	const entries = await readdir(connectionsDir);
	const rows: string[] = [];

	for (const name of entries.filter((entry) => entry.endsWith('.md') && entry !== 'README.md' && entry !== 'INDEX.md').sort()) {
		const text = await readFile(join(connectionsDir, name), 'utf8');
		const frontmatter = text.match(frontmatterPattern)?.[1];
		const parsed = frontmatter ? ConnectionDoc.safeParse(parse(frontmatter)) : undefined;

		if (!parsed?.success) {
			continue;
		}

		const summary =
			text
				.slice(text.indexOf('---', 4) + 3)
				.split('\n')
				.map((line) => line.trim())
				.find((line) => line && !line.startsWith('#')) ?? '';

		rows.push(`| ${parsed.data.from} | ${parsed.data.to} | ${parsed.data.type} | ${summary} | [${name}](${name}) |`);
	}

	const index = [
		'# Connection index',
		'',
		'<!-- Regenerated by lightsout build-map — do not edit by hand. -->',
		'',
		'| from | to | type | summary | doc |',
		'|---|---|---|---|---|',
		...rows,
		'',
	].join('\n');

	await writeFile(join(connectionsDir, 'INDEX.md'), index, 'utf8');

	return { edgeCount: rows.length };
};
