export { checkConfiguredPaths } from '#src/doctor/checkConfiguredPaths.ts';
export { checkCoverageSummary } from '#src/doctor/checkCoverageSummary.ts';
export { checkGitignore } from '#src/doctor/checkGitignore.ts';
export { checkHarness } from '#src/doctor/checkHarness.ts';
export { checkJestMocks } from '#src/doctor/checkJestMocks.ts';
export { checkLintRules } from '#src/doctor/checkLintRules.ts';
export { checkScriptBinaries } from '#src/doctor/checkScriptBinaries.ts';
export { checkUserEvent } from '#src/doctor/checkUserEvent.ts';
export { runDoctor } from '#src/doctor/runDoctor.ts';
