#!/usr/bin/env node
// Regenerates the engine's default-standards barrels from the standards/
// folders. Run from the repo root whenever docs are added, removed, or
// renamed: node tools/generateStandardsBarrels.mjs
import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

const build = ({ channel, exportName }) => {
	const files = execSync(`find standards/${channel} -name '*.md' | sort`).toString().trim().split('\n').filter(Boolean);
	const imports = files.map((file, index) => `import doc${index} from '../../../${file}';`).join('\n');
	const entries = files
		.map((file, index) => '\t`<!-- lightsout defaults: ' + file + ' -->\\n${doc' + index + '}`,')
		.join('\n');
	const content = `// GENERATED by tools/generateStandardsBarrels.mjs from standards/${channel}/ — do not edit by hand.
${imports}

/** Every default ${channel} standards doc, concatenated in path order with per-file provenance headers. */
export const ${exportName} = [
${entries}
].join('\\n\\n');
`;

	writeFileSync(`packages/engine/src/${exportName}.ts`, content);
	console.log(`${exportName}.ts: ${files.length} docs`);
};

build({ channel: 'code', exportName: 'defaultCodeStandards' });
build({ channel: 'tests', exportName: 'defaultTestStandards' });
