#!/usr/bin/env node
// Regenerates the engine's default-standards barrels from the standards/
// folders. Run from the repo root whenever docs are added, removed, or
// renamed: node tools/generateStandardsBarrels.mjs
//
// Docs are grouped into CHANNELS by path: a path containing "tanstack" →
// tanstack channel, containing "react" → react channel, anything else →
// base. The engine injects base always and the framework channels only when
// the run's package scope actually uses that framework (or the consumer's
// `standardsChannels` config says so).
import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

const channelOf = (file) => (file.includes('tanstack') ? 'tanstack' : file.includes('react') ? 'react' : 'base');

const build = ({ tree, exportName }) => {
	const files = execSync(`find standards/${tree} -name '*.md' | sort`).toString().trim().split('\n').filter(Boolean);
	const imports = files.map((file, index) => `import doc${index} from '../../${file}';`).join('\n');
	const channels = new Map();

	files.forEach((file, index) => {
		const channel = channelOf(file);

		if (!channels.has(channel)) {
			channels.set(channel, []);
		}

		channels.get(channel).push({ file, index });
	});

	const channelEntries = [...channels.entries()]
		.map(([channel, docs]) => {
			const entries = docs
				.map(({ file, index }) => '\t\t`<!-- lightsout defaults: ' + file + ' -->\\n${doc' + index + '}`,')
				.join('\n');

			return `\t${channel}: [\n${entries}\n\t].join('\\n\\n'),`;
		})
		.join('\n');

	const content = `// GENERATED by tools/generateStandardsBarrels.mjs from standards/${tree}/ — do not edit by hand.
${imports}

/** Default ${tree} standards docs by channel: base always applies; framework channels apply when the package scope uses that framework. */
export const ${exportName}: Record<string, string> = {
${channelEntries}
};
`;

	writeFileSync(`src/standards/${exportName}.ts`, content);
	console.log(`${exportName}.ts: ${files.length} docs across channels [${[...channels.keys()].join(', ')}]`);
};

build({ tree: 'code', exportName: 'defaultCodeStandards' });
build({ tree: 'tests', exportName: 'defaultTestStandards' });
