#!/usr/bin/env node
// Regenerates the engine's default-standards barrels from the standards/
// folders. Run from the repo root whenever docs are added, removed, or
// renamed: node tools/generateStandardsBarrels.ts
//
// Runs under Node's native type stripping — no build step and no dependency,
// which is why this stays a directly-executed script rather than something the
// bundler owns.
//
// Docs are grouped into CHANNELS by path: a path containing "tanstack" →
// tanstack channel, containing "react" → react channel, anything else →
// base. The engine injects base always and the framework channels only when
// the run's package scope actually uses that framework (or the consumer's
// `standardsChannels` config says so).
import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

/** One doc's place in the emitted barrel: its repo-relative path and its `docN` import index. */
interface ChannelDoc {
	file: string;
	index: number;
}

const channelOf = ({ file }: { file: string }) => (file.includes('tanstack') ? 'tanstack' : file.includes('react') ? 'react' : 'base');

const build = ({ tree, exportName }: { tree: string; exportName: string }) => {
	const files = execSync(`find standards/${tree} -name '*.md' | sort`).toString().trim().split('\n').filter(Boolean);
	const imports = files.map((file, index) => `import doc${index} from '../../${file}';`).join('\n');
	const channels = new Map<string, ChannelDoc[]>();

	files.forEach((file, index) => {
		const channel = channelOf({ file });
		const docs = channels.get(channel) ?? [];

		docs.push({ file, index });
		channels.set(channel, docs);
	});

	const channelEntries = [...channels.entries()]
		.map(([channel, docs]) => {
			const entries = docs
				.map(({ file, index }) => '\t\t`<!-- lightsout defaults: ' + file + ' -->\\n${doc' + index + '}`,')
				.join('\n');

			return `\t${channel}: [\n${entries}\n\t].join('\\n\\n'),`;
		})
		.join('\n');

	const content = `// GENERATED by tools/generateStandardsBarrels.ts from standards/${tree}/ — do not edit by hand.
${imports}

/** Default ${tree} standards docs by channel: base always applies; framework channels apply when the package scope uses that framework. */
export const ${exportName}: Record<string, string> = {
${channelEntries}
};
`;

	writeFileSync(`src/standards/${exportName}.ts`, content);
	console.log(`${exportName}.ts: ${files.length} docs across channels [${[...channels.keys()].join(', ')}]`);
};

build({ tree: 'code', exportName: 'defaultCodeStandards' });
build({ tree: 'tests', exportName: 'defaultTestStandards' });
